# Generated by Django 4.2.7 on 2025-07-13 21:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100, unique=True, verbose_name='الكلمة المحظورة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'كلمة محظورة',
                'verbose_name_plural': 'الكلمات المحظورة',
                'ordering': ['word'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التصنيف')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(blank=True, verbose_name='وصف التصنيف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تصنيف',
                'verbose_name_plural': 'التصنيفات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم المنتج')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط المختصر')),
                ('description', models.TextField(verbose_name='وصف المنتج')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='صورة المنتج')),
                ('is_active', models.BooleanField(default=True, verbose_name='متاح للبيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='blog.category', verbose_name='التصنيف')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التقييم')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المراجعة')),
                ('content', models.TextField(verbose_name='محتوى المراجعة')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='مرفوض')),
                ('sentiment', models.CharField(blank=True, choices=[('positive', 'إيجابي'), ('negative', 'سلبي'), ('neutral', 'محايد')], max_length=10, verbose_name='الانطباع')),
                ('helpful_votes', models.PositiveIntegerField(default=0, verbose_name='أصوات مفيدة')),
                ('unhelpful_votes', models.PositiveIntegerField(default=0, verbose_name='أصوات غير مفيدة')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='blog.product', verbose_name='المنتج')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مراجعة',
                'verbose_name_plural': 'المراجعات',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المقال')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='الرابط المختصر')),
                ('content', models.TextField(verbose_name='محتوى المقال')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='ملخص المقال')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='الصورة المميزة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشور')], default='draft', max_length=10, verbose_name='الحالة')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blog.category', verbose_name='التصنيف')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL, verbose_name='الإعجابات')),
            ],
            options={
                'verbose_name': 'مقال',
                'verbose_name_plural': 'المقالات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('review_approved', 'موافقة على المراجعة'), ('review_rejected', 'رفض المراجعة'), ('review_reply', 'رد على المراجعة'), ('product_update', 'تحديث المنتج'), ('review_reported', 'إبلاغ عن مراجعة')], max_length=20, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='رسالة الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='معرف الكائن المرتبط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='محتوى التعليق')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافق عليه')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='الكاتب')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment', verbose_name='التعليق الأب')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='المقال')),
            ],
            options={
                'verbose_name': 'تعليق',
                'verbose_name_plural': 'التعليقات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReviewReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'محتوى غير مناسب'), ('spam', 'رسائل مزعجة'), ('fake', 'مراجعة مزيفة'), ('offensive', 'محتوى مسيء'), ('other', 'أخرى')], max_length=20, verbose_name='سبب البلاغ')),
                ('description', models.TextField(blank=True, verbose_name='وصف إضافي')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='تم الحل')),
                ('admin_notes', models.TextField(blank=True, verbose_name='ملاحظات الإدارة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البلاغ')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_reports', to=settings.AUTH_USER_MODEL, verbose_name='المبلغ')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='blog.review', verbose_name='المراجعة')),
            ],
            options={
                'verbose_name': 'بلاغ مراجعة',
                'verbose_name_plural': 'بلاغات المراجعات',
                'ordering': ['-created_at'],
                'unique_together': {('review', 'reporter')},
            },
        ),
        migrations.CreateModel(
            name='ReviewInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('helpful', 'مفيدة'), ('unhelpful', 'غير مفيدة')], max_length=10, verbose_name='نوع التفاعل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التفاعل')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='blog.review', verbose_name='المراجعة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_interactions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تفاعل المراجعة',
                'verbose_name_plural': 'تفاعلات المراجعات',
                'ordering': ['-created_at'],
                'unique_together': {('review', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='blog.post', verbose_name='المقال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'مفضلة',
                'verbose_name_plural': 'المفضلات',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'post')},
            },
        ),
    ]
